#%RAML 1.0 NamedExample

AggregateUsersAndCount:
  users:
  -
    id: 61bf44ab49c9437612e1ab6e
    created_at: 2021-12-19T09:47:38Z
    updated_at: 2021-12-19T09:47:38Z
    fname: gogo
    lname: odem
    email: oghogho@inflow.finance
    dob: 1997-02-18
    role: ADMIN
    like_ids:
    - 61bf44ab49c9437612e1ab6e
    likes:
    -
      name: Action
      icon: https://www.nyfa.edu/student-resources/wp-content/uploads/2015/03/action-movie-1024x640.jpg
  count: 3
