#%RAML 1.0 NamedExample

CategoriesAndCount:
  categories:
  -
    id: 61bf44ab49c9437612e1ab6e
    created_at: 2021-12-19T09:47:38Z
    updated_at: 2021-12-19T09:47:38Z
    name: Action
    icon: https://www.nyfa.edu/student-resources/wp-content/uploads/2015/03/action-movie-1024x640.jpg
  count: 3
