responses:
  400:
    body:
      type: responses.GenericResponse
      examples: !include ../examples/responses/validation_error_response.raml
    description: one or more values in the request is missing or invalid
