responses:
  404:
    body:
      type: responses.GenericResponse
      examples: !include ../examples/responses/notfound_error_response.raml
    description: the requested <<resource>> does not exist
