responses:
  401:
    body:
      type: responses.GenericResponse
      examples: !include ../examples/responses/invalid_token_error_response.raml
    description: the token used to authorize the request is invalid
