queryParameters:
  page:
    required: false
    type: integer
    description: the offset of the list being returned with respect to the [limit]
    default: 1
    minimum: 1
  limit:
    required: false
    type: integer
    description: the maximum number of entries in the list being returned
    default: 1
    minimum: 1
