has_validation_error: !include has_validation_error.raml
has_conflict_error: !include has_conflict_error.raml
has_notfound_error: !include has_notfound_error.raml
has_token_error: !include has_invalid_token_error.raml
paginated: !include paginated.raml
