version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 55059:55059
    restart: unless-stopped
    environment:
      - DB_NAME=prologue_server
      - DB_URL=mongodb://mongo:27017/prologue_server
      - APP_PORT=55059
      - APP_ENV=playground
  mongo:
    image: mongo:5.0
    logging:
      driver: "none"
    volumes:
      - ~/mongodb/db:/data/db
    expose:
      - 27017
  docs:
    image: gcr.io/api-console-a6952/app:0.1.0
    volumes:
      - ${PWD}/docs:/app/api
    ports:
      - 8080:8080
    environment:
      - API_PROJECT=api.raml
      - API_TYPE=RAML 1.0
      - API_MIME=application/raml
